version: '3.8'

services:
  nifi:
    image: apache/nifi:2.0.0-M1
    ports:
      - "10433:10433"
        # Remote Input Socket
        #- 10000:10000/tcp
        # JVM Debugger
        #- 8000:8000/tcp
        # Cluster Node Protocol
        #- 11443:11443/tcp
    volumes:
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./:/app
    environment:
      - NIFI_WEB_HTTPS_HOST=nifi
      # In your proxy, your origin has to send X-ProxyScheme, X-ProxyPort and X-ProxyContextPath headers
      # In my case, https://community.cloudflare.com/t/add-extra-headers-to-backend-services/373525
      - NIFI_WEB_PROXY_HOST=nifi.sanchezcarlosjr.com
      - NIFI_WEB_HTTPS_PORT=10433
      - NIFI_JVM_HEAP_MAX=8192m
      - NIFI_BASE_DIR=./nifi
      - SINGLE_USER_CREDENTIALS_USERNAME=${ADMIN_USER_EMAIL}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${ADMIN_USER_PASSWORD}

networks:
  default:
    external: true
    name: supabase_default
